// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:holo/entity/actor.dart';
import 'package:holo/entity/anime_info.dart';
import 'package:holo/entity/daily_broadcast.dart';
import 'package:holo/entity/daily_mantra.dart';
import 'package:holo/entity/image.dart';
import 'package:holo/entity/rule.dart';
import 'package:holo/entity/user.dart';
import 'package:holo/entity/user_playback.dart';
import 'package:holo/entity/user_setting.dart';
import 'package:holo/entity/user_subscribe.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ActorAdapter());
    registerAdapter(AnimeInfoAdapter());
    registerAdapter(DailyBroadcastAdapter());
    registerAdapter(DailyMantraAdapter());
    registerAdapter(ImageAdapter());
    registerAdapter(RequestMethodAdapter());
    registerAdapter(RuleAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserPlaybackAdapter());
    registerAdapter(UserSettingAdapter());
    registerAdapter(UserSubscribeAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ActorAdapter());
    registerAdapter(AnimeInfoAdapter());
    registerAdapter(DailyBroadcastAdapter());
    registerAdapter(DailyMantraAdapter());
    registerAdapter(ImageAdapter());
    registerAdapter(RequestMethodAdapter());
    registerAdapter(RuleAdapter());
    registerAdapter(UserAdapter());
    registerAdapter(UserPlaybackAdapter());
    registerAdapter(UserSettingAdapter());
    registerAdapter(UserSubscribeAdapter());
  }
}
